// Maps a generated mod token `id` to its PoE2 trade stat id.
// Generated by scripts/fetch-trade-stats.mjs into public/generated/trade.
export type TradeStatIdMap = Record<string, string>;

function load(file: string): Promise<TradeStatIdMap> {
  return fetch(file)
    .then((r) => (r.ok ? (r.json() as Promise<TradeStatIdMap>) : {}))
    .catch(() => ({}));
}

let waystoneCache: Promise<TradeStatIdMap> | null = null;
let tabletCache: Promise<TradeStatIdMap> | null = null;

export function loadWaystoneTradeStatIds(): Promise<TradeStatIdMap> {
  if (!waystoneCache) {
    waystoneCache = load("/generated/trade/WaystoneTradeStatIds.json");
  }
  return waystoneCache;
}

export function loadTabletTradeStatIds(): Promise<TradeStatIdMap> {
  if (!tabletCache) {
    tabletCache = load("/generated/trade/TabletTradeStatIds.json");
  }
  return tabletCache;
}
